// Builds the arkdevs website into dist/: prerendered HTML for every page, plus sitemap,
// robots, manifest and the other files search engines and browsers look for.
// Node standard library only:  node build.mjs   (SITE_URL=https://example.com to change origin)
import { createHash } from 'node:crypto';
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { site, services, projects } from './src/data.mjs';
import { FONT } from './src/lib/dotfont.mjs';
import * as t from './src/templates.mjs';

const root = dirname(fileURLToPath(import.meta.url));
const src = join(root, 'src');
const out = join(root, 'dist');
const today = new Date().toISOString().slice(0, 10);

rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });

// Static assets, and root files (favicons, touch icons) generated by `npm run assets`.
cpSync(join(src, 'assets'), join(out, 'assets'), { recursive: true });
if (existsSync(join(src, 'static'))) cpSync(join(src, 'static'), out, { recursive: true });

// The dot-matrix font is shared with the browser: one source of truth for every glyph.
writeFileSync(join(out, 'assets/js/dotfont.js'), `window.DOTFONT=${JSON.stringify(FONT)};\n`);
const siteJs = readFileSync(join(out, 'assets/js/dotfont.js'), 'utf8') + readFileSync(join(src, 'assets/js/site.js'), 'utf8');
writeFileSync(join(out, 'assets/js/site.js'), siteJs);
rmSync(join(out, 'assets/js/dotfont.js'));

const hash = (s) => createHash('sha256').update(s).digest('hex').slice(0, 10);
const assets = {
  css: hash(readFileSync(join(out, 'assets/css/site.css'))),
  js: hash(siteJs),
};

// path '' is the home page; 'work/arkstore/' a nested one. Links are relative so the
// site works at a domain root, under a sub-path, or opened from disk.
const relFor = (path) => (path === '' ? './' : '../'.repeat(path.split('/').filter(Boolean).length));
const basePath = new URL(site.url + '/').pathname;

const pages = [];
function page({ path, title, description, og, priority = '0.7', changefreq = 'monthly', render, pageClass }) {
  const rel = relFor(path);
  const { body, schema } = render(rel);
  const html = t.layout({ path, title, description, og, schema, body, pageClass, rel, assets });
  const file = join(out, path, 'index.html');
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, html);
  pages.push({ path, title, description, priority, changefreq });
}

page({
  path: '',
  title: 'Software Development Company in Sri Lanka',
  description: site.metaDescription,
  og: 'home',
  priority: '1.0',
  changefreq: 'weekly',
  pageClass: 'page-home',
  render: t.homePage,
});
page({
  path: 'services/',
  title: 'Software Development Services',
  description:
    'Custom software and ERP, web applications, Android and iOS apps, desktop apps, database engineering and AI integration, from one team in Colombo, Sri Lanka.',
  og: 'services',
  priority: '0.9',
  render: t.servicesPage,
});
for (const s of services) {
  page({ path: `services/${s.slug}/`, title: s.seoTitle, description: s.description, og: `service-${s.slug}`, priority: '0.8', render: (rel) => t.servicePage(rel, s) });
}
page({
  path: 'work/',
  title: 'Our Work: Products & Case Studies',
  description: `${projects.length} products and systems built by arkdevs: ${projects
    .slice(0, 5)
    .map((p) => p.name)
    .join(', ')} and more. App stores, ERPs, IDEs and AI assistants in production.`,
  og: 'work',
  priority: '0.9',
  changefreq: 'weekly',
  render: t.workPage,
});
for (const p of projects) {
  page({
    path: `work/${p.slug}/`,
    title: `${p.name}: ${p.kind === 'Client' ? 'Case Study' : p.tags.includes('Open source') ? 'Open-Source ' + (p.tags.includes('AI') ? 'AI App' : 'Software') : 'Project'}`,
    description: p.description.length <= 160 ? p.description : `${p.name}: ${p.summary} ${p.kind === 'Client' ? 'A case study' : 'Open source'} by arkdevs.`,
    og: `work-${p.slug}`,
    priority: p.kind === 'Product' ? '0.8' : '0.7',
    render: (rel) => t.projectPage(rel, p),
    pageClass: 'page-case',
  });
}
page({
  path: 'about/',
  title: 'About Us',
  description: `arkdevs is a software solutions company in ${site.city}, ${site.country}, founded in ${site.foundingYear}. Meet the team, our principles and how we work.`,
  og: 'about',
  priority: '0.7',
  render: t.aboutPage,
});
page({
  path: 'contact/',
  title: 'Contact Us: Start a Project',
  description: `Start a software project with arkdevs. Email ${site.email} or call ${site.phone}. We reply within one business day.`,
  og: 'contact',
  priority: '0.8',
  render: t.contactPage,
});
page({
  path: 'privacy/',
  title: 'Privacy Policy',
  description: 'How the arkdevs website handles your data: no tracking cookies, no third-party analytics.',
  og: 'home',
  priority: '0.2',
  changefreq: 'yearly',
  render: t.privacyPage,
});

// 404: served by the host for any missing path, so its links must be absolute.
{
  const { body } = t.notFoundPage(basePath);
  const html = t
    .layout({ path: '404', title: 'Page not found', description: 'This page does not exist.', og: 'home', schema: [], body, rel: basePath, assets, pageClass: 'page-404' })
    .replace('<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1">', '<meta name="robots" content="noindex">')
    .replace(/<link rel="canonical"[^>]*>\n/, '');
  writeFileSync(join(out, '404.html'), html);
}

// ---------------------------------------------------------------- crawler files

const loc = (path) => `${site.url}/${path}`;
writeFileSync(
  join(out, 'sitemap.xml'),
  `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
${pages
  .map((p) => {
    const proj = projects.find((x) => p.path === `work/${x.slug}/`);
    const imgs = (proj?.images || []).filter((i) => !i.src.endsWith('.svg'));
    return `  <url>
    <loc>${loc(p.path)}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${p.changefreq}</changefreq>
    <priority>${p.priority}</priority>${imgs.map((i) => `\n    <image:image><image:loc>${loc('assets/img/' + i.src)}</image:loc></image:image>`).join('')}
  </url>`;
  })
  .join('\n')}
</urlset>
`,
);

writeFileSync(
  join(out, 'robots.txt'),
  `# ${site.name}
User-agent: *
Allow: /
Disallow: ${basePath}404.html

Sitemap: ${site.url}/sitemap.xml
`,
);

writeFileSync(
  join(out, 'site.webmanifest'),
  JSON.stringify(
    {
      name: site.name,
      short_name: site.name,
      description: site.shortDescription,
      start_url: basePath,
      scope: basePath,
      display: 'standalone',
      background_color: '#111111',
      theme_color: '#111111',
      icons: [
        { src: 'icon-192.png', sizes: '192x192', type: 'image/png' },
        { src: 'icon-512.png', sizes: '512x512', type: 'image/png' },
        { src: 'icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        { src: 'favicon.svg', sizes: 'any', type: 'image/svg+xml' },
      ],
    },
    null,
    2,
  ),
);

// A plain-text summary for AI search engines and assistants (llmstxt.org).
writeFileSync(
  join(out, 'llms.txt'),
  `# ${site.name}

> ${site.description}

- Location: ${site.city}, ${site.country} (${site.timezone}); works with clients worldwide
- Contact: ${site.email}, ${site.phone}
- GitHub: ${site.github}

## Services
${services.map((s) => `- [${s.title}](${loc(`services/${s.slug}/`)}): ${s.short}`).join('\n')}

## Work
${projects.map((p) => `- [${p.name}](${loc(`work/${p.slug}/`)}) (${p.kind}, ${p.year}): ${p.summary}`).join('\n')}

## Pages
- [About](${loc('about/')})
- [Contact](${loc('contact/')})
`,
);

writeFileSync(
  join(out, 'humans.txt'),
  `/* TEAM */
Company: ${site.name}
Founder: ${site.founder.name}
Location: ${site.city}, ${site.country}
Contact: ${site.email}

/* SITE */
Last update: ${today}
Standards: HTML5, CSS3, Schema.org
Fonts: Sora, Space Mono
Motion: GSAP, ScrollTrigger, Lenis
`,
);

mkdirSync(join(out, '.well-known'), { recursive: true });
const nextYear = new Date(Date.now() + 365 * 864e5).toISOString().replace(/\.\d+Z$/, 'Z');
writeFileSync(join(out, '.well-known/security.txt'), `Contact: mailto:${site.issuesEmail}\nExpires: ${nextYear}\nPreferred-Languages: en\nCanonical: ${site.url}/.well-known/security.txt\n`);

// GitHub Pages: serve files as-is, and a custom domain if SITE_URL is not *.github.io.
writeFileSync(join(out, '.nojekyll'), '');
const host = new URL(site.url).host;
if (!host.endsWith('github.io') && !host.startsWith('localhost')) writeFileSync(join(out, 'CNAME'), host + '\n');

console.log(`Built ${pages.length} pages for ${site.url} into dist/`);
